"""data1.5

Revision ID: 139ead4278c6
Revises: 42d28fc0cfba
Create Date: 2020-10-15 02:51:48.654873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139ead4278c6'
down_revision = '42d28fc0cfba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_pdf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
