"""añadiendo category

Revision ID: 405f3e5972ef
Revises: eb241d76ccd5
Create Date: 2020-10-08 12:09:26.296820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405f3e5972ef'
down_revision = 'eb241d76ccd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('category', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'category')
    # ### end Alembic commands ###
