"""coments y favoritos

Revision ID: 42d28fc0cfba
Revises: d071dc80ca7b
Create Date: 2020-10-15 02:49:20.031248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d28fc0cfba'
down_revision = 'd071dc80ca7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Coments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_user_pdf', sa.Integer(), nullable=True),
    sa.Column('id_pdf', sa.Integer(), nullable=True),
    sa.Column('title_coments', sa.String(length=256), nullable=False),
    sa.Column('uptime', sa.DateTime(), nullable=True),
    sa.Column('post', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Coments')
    # ### end Alembic commands ###
