"""texto en la tabla files

Revision ID: 4d9c3bdc430a
Revises: 40de0defc0d6
Create Date: 2020-10-19 20:03:43.970559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9c3bdc430a'
down_revision = '40de0defc0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('texto_completo', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'texto_completo')
    # ### end Alembic commands ###
