"""actualizacion datetime

Revision ID: 569bcfbd0971
Revises: f7b22c57b57c
Create Date: 2020-09-21 21:40:46.274041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569bcfbd0971'
down_revision = 'f7b22c57b57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('uptime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'uptime')
    # ### end Alembic commands ###
