"""titulo unico de pdf

Revision ID: af81e49a8f38
Revises: 8b1fc8e63da9
Create Date: 2020-10-15 11:29:44.469605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af81e49a8f38'
down_revision = '8b1fc8e63da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'files', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    # ### end Alembic commands ###
