"""prueba1

Revision ID: d071dc80ca7b
Revises: 6a4eab0617ab
Create Date: 2020-10-15 02:27:24.553435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd071dc80ca7b'
down_revision = '6a4eab0617ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'files', 'account', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    # ### end Alembic commands ###
