"""cambio nombre coments

Revision ID: d1eb2c836163
Revises: af81e49a8f38
Create Date: 2020-10-15 18:09:34.579233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1eb2c836163'
down_revision = 'af81e49a8f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('username_pdf', sa.String(length=80), nullable=False),
    sa.Column('id_pdf', sa.Integer(), nullable=True),
    sa.Column('title_coments', sa.String(length=256), nullable=False),
    sa.Column('uptime', sa.DateTime(), nullable=True),
    sa.Column('post', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Coments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Coments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Coments_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_pdf', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title_coments', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('uptime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('post', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('username_pdf', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['account.id'], name='Coments_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='Coments_pkey')
    )
    op.drop_table('coments')
    # ### end Alembic commands ###
